/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/app.tasks'
import { Route as AuthenticatedAppSiteVisitsRouteImport } from './routes/_authenticated/app.site-visits'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppReceiptsRouteImport } from './routes/_authenticated/app.receipts'
import { Route as AuthenticatedAppQuotationsRouteImport } from './routes/_authenticated/app.quotations'
import { Route as AuthenticatedAppProjectsRouteImport } from './routes/_authenticated/app.projects'
import { Route as AuthenticatedAppPlotsRouteImport } from './routes/_authenticated/app.plots'
import { Route as AuthenticatedAppPaymentsRouteImport } from './routes/_authenticated/app.payments'
import { Route as AuthenticatedAppOpportunitiesRouteImport } from './routes/_authenticated/app.opportunities'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppFollowUpsRouteImport } from './routes/_authenticated/app.follow-ups'
import { Route as AuthenticatedAppDealsRouteImport } from './routes/_authenticated/app.deals'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/app.customers'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/app.calendar'
import { Route as AuthenticatedAppBookingsRouteImport } from './routes/_authenticated/app.bookings'
import { Route as AuthenticatedAppSettingsUsersRouteImport } from './routes/_authenticated/app.settings.users'
import { Route as AuthenticatedAppSettingsOrganizationRouteImport } from './routes/_authenticated/app.settings.organization'
import { Route as AuthenticatedAppLeadsNewRouteImport } from './routes/_authenticated/app.leads.new'
import { Route as AuthenticatedAppLeadsLeadIdRouteImport } from './routes/_authenticated/app.leads.$leadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSiteVisitsRoute =
  AuthenticatedAppSiteVisitsRouteImport.update({
    id: '/site-visits',
    path: '/site-visits',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReceiptsRoute =
  AuthenticatedAppReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuotationsRoute =
  AuthenticatedAppQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsRoute =
  AuthenticatedAppProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPlotsRoute = AuthenticatedAppPlotsRouteImport.update({
  id: '/plots',
  path: '/plots',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPaymentsRoute =
  AuthenticatedAppPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpportunitiesRoute =
  AuthenticatedAppOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFollowUpsRoute =
  AuthenticatedAppFollowUpsRouteImport.update({
    id: '/follow-ups',
    path: '/follow-ups',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDealsRoute = AuthenticatedAppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBookingsRoute =
  AuthenticatedAppBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsUsersRoute =
  AuthenticatedAppSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsOrganizationRoute =
  AuthenticatedAppSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsNewRoute =
  AuthenticatedAppLeadsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppLeadsRoute,
  } as any)
const AuthenticatedAppLeadsLeadIdRoute =
  AuthenticatedAppLeadsLeadIdRouteImport.update({
    id: '/$leadId',
    path: '/$leadId',
    getParentRoute: () => AuthenticatedAppLeadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/bookings': typeof AuthenticatedAppBookingsRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/deals': typeof AuthenticatedAppDealsRoute
  '/app/follow-ups': typeof AuthenticatedAppFollowUpsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRouteWithChildren
  '/app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/plots': typeof AuthenticatedAppPlotsRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/quotations': typeof AuthenticatedAppQuotationsRoute
  '/app/receipts': typeof AuthenticatedAppReceiptsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/site-visits': typeof AuthenticatedAppSiteVisitsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/leads/$leadId': typeof AuthenticatedAppLeadsLeadIdRoute
  '/app/leads/new': typeof AuthenticatedAppLeadsNewRoute
  '/app/settings/organization': typeof AuthenticatedAppSettingsOrganizationRoute
  '/app/settings/users': typeof AuthenticatedAppSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/bookings': typeof AuthenticatedAppBookingsRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/customers': typeof AuthenticatedAppCustomersRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/deals': typeof AuthenticatedAppDealsRoute
  '/app/follow-ups': typeof AuthenticatedAppFollowUpsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRouteWithChildren
  '/app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/app/plots': typeof AuthenticatedAppPlotsRoute
  '/app/projects': typeof AuthenticatedAppProjectsRoute
  '/app/quotations': typeof AuthenticatedAppQuotationsRoute
  '/app/receipts': typeof AuthenticatedAppReceiptsRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/site-visits': typeof AuthenticatedAppSiteVisitsRoute
  '/app/tasks': typeof AuthenticatedAppTasksRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/leads/$leadId': typeof AuthenticatedAppLeadsLeadIdRoute
  '/app/leads/new': typeof AuthenticatedAppLeadsNewRoute
  '/app/settings/organization': typeof AuthenticatedAppSettingsOrganizationRoute
  '/app/settings/users': typeof AuthenticatedAppSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/bookings': typeof AuthenticatedAppBookingsRoute
  '/_authenticated/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/customers': typeof AuthenticatedAppCustomersRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/deals': typeof AuthenticatedAppDealsRoute
  '/_authenticated/app/follow-ups': typeof AuthenticatedAppFollowUpsRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRouteWithChildren
  '/_authenticated/app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/_authenticated/app/payments': typeof AuthenticatedAppPaymentsRoute
  '/_authenticated/app/plots': typeof AuthenticatedAppPlotsRoute
  '/_authenticated/app/projects': typeof AuthenticatedAppProjectsRoute
  '/_authenticated/app/quotations': typeof AuthenticatedAppQuotationsRoute
  '/_authenticated/app/receipts': typeof AuthenticatedAppReceiptsRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/site-visits': typeof AuthenticatedAppSiteVisitsRoute
  '/_authenticated/app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/leads/$leadId': typeof AuthenticatedAppLeadsLeadIdRoute
  '/_authenticated/app/leads/new': typeof AuthenticatedAppLeadsNewRoute
  '/_authenticated/app/settings/organization': typeof AuthenticatedAppSettingsOrganizationRoute
  '/_authenticated/app/settings/users': typeof AuthenticatedAppSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/deals'
    | '/app/follow-ups'
    | '/app/leads'
    | '/app/opportunities'
    | '/app/payments'
    | '/app/plots'
    | '/app/projects'
    | '/app/quotations'
    | '/app/receipts'
    | '/app/reports'
    | '/app/site-visits'
    | '/app/tasks'
    | '/app/'
    | '/app/leads/$leadId'
    | '/app/leads/new'
    | '/app/settings/organization'
    | '/app/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/customers'
    | '/app/dashboard'
    | '/app/deals'
    | '/app/follow-ups'
    | '/app/leads'
    | '/app/opportunities'
    | '/app/payments'
    | '/app/plots'
    | '/app/projects'
    | '/app/quotations'
    | '/app/receipts'
    | '/app/reports'
    | '/app/site-visits'
    | '/app/tasks'
    | '/app'
    | '/app/leads/$leadId'
    | '/app/leads/new'
    | '/app/settings/organization'
    | '/app/settings/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/bookings'
    | '/_authenticated/app/calendar'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/customers'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/deals'
    | '/_authenticated/app/follow-ups'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/opportunities'
    | '/_authenticated/app/payments'
    | '/_authenticated/app/plots'
    | '/_authenticated/app/projects'
    | '/_authenticated/app/quotations'
    | '/_authenticated/app/receipts'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/site-visits'
    | '/_authenticated/app/tasks'
    | '/_authenticated/app/'
    | '/_authenticated/app/leads/$leadId'
    | '/_authenticated/app/leads/new'
    | '/_authenticated/app/settings/organization'
    | '/_authenticated/app/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/tasks': {
      id: '/_authenticated/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/site-visits': {
      id: '/_authenticated/app/site-visits'
      path: '/site-visits'
      fullPath: '/app/site-visits'
      preLoaderRoute: typeof AuthenticatedAppSiteVisitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/receipts': {
      id: '/_authenticated/app/receipts'
      path: '/receipts'
      fullPath: '/app/receipts'
      preLoaderRoute: typeof AuthenticatedAppReceiptsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quotations': {
      id: '/_authenticated/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AuthenticatedAppQuotationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects': {
      id: '/_authenticated/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AuthenticatedAppProjectsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/plots': {
      id: '/_authenticated/app/plots'
      path: '/plots'
      fullPath: '/app/plots'
      preLoaderRoute: typeof AuthenticatedAppPlotsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/payments': {
      id: '/_authenticated/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AuthenticatedAppPaymentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/opportunities': {
      id: '/_authenticated/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AuthenticatedAppOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/follow-ups': {
      id: '/_authenticated/app/follow-ups'
      path: '/follow-ups'
      fullPath: '/app/follow-ups'
      preLoaderRoute: typeof AuthenticatedAppFollowUpsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deals': {
      id: '/_authenticated/app/deals'
      path: '/deals'
      fullPath: '/app/deals'
      preLoaderRoute: typeof AuthenticatedAppDealsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/customers': {
      id: '/_authenticated/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendar': {
      id: '/_authenticated/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bookings': {
      id: '/_authenticated/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AuthenticatedAppBookingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/users': {
      id: '/_authenticated/app/settings/users'
      path: '/settings/users'
      fullPath: '/app/settings/users'
      preLoaderRoute: typeof AuthenticatedAppSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/organization': {
      id: '/_authenticated/app/settings/organization'
      path: '/settings/organization'
      fullPath: '/app/settings/organization'
      preLoaderRoute: typeof AuthenticatedAppSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads/new': {
      id: '/_authenticated/app/leads/new'
      path: '/new'
      fullPath: '/app/leads/new'
      preLoaderRoute: typeof AuthenticatedAppLeadsNewRouteImport
      parentRoute: typeof AuthenticatedAppLeadsRoute
    }
    '/_authenticated/app/leads/$leadId': {
      id: '/_authenticated/app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/app/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedAppLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedAppLeadsRoute
    }
  }
}

interface AuthenticatedAppLeadsRouteChildren {
  AuthenticatedAppLeadsLeadIdRoute: typeof AuthenticatedAppLeadsLeadIdRoute
  AuthenticatedAppLeadsNewRoute: typeof AuthenticatedAppLeadsNewRoute
}

const AuthenticatedAppLeadsRouteChildren: AuthenticatedAppLeadsRouteChildren = {
  AuthenticatedAppLeadsLeadIdRoute: AuthenticatedAppLeadsLeadIdRoute,
  AuthenticatedAppLeadsNewRoute: AuthenticatedAppLeadsNewRoute,
}

const AuthenticatedAppLeadsRouteWithChildren =
  AuthenticatedAppLeadsRoute._addFileChildren(
    AuthenticatedAppLeadsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBookingsRoute: typeof AuthenticatedAppBookingsRoute
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppDealsRoute: typeof AuthenticatedAppDealsRoute
  AuthenticatedAppFollowUpsRoute: typeof AuthenticatedAppFollowUpsRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRouteWithChildren
  AuthenticatedAppOpportunitiesRoute: typeof AuthenticatedAppOpportunitiesRoute
  AuthenticatedAppPaymentsRoute: typeof AuthenticatedAppPaymentsRoute
  AuthenticatedAppPlotsRoute: typeof AuthenticatedAppPlotsRoute
  AuthenticatedAppProjectsRoute: typeof AuthenticatedAppProjectsRoute
  AuthenticatedAppQuotationsRoute: typeof AuthenticatedAppQuotationsRoute
  AuthenticatedAppReceiptsRoute: typeof AuthenticatedAppReceiptsRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSiteVisitsRoute: typeof AuthenticatedAppSiteVisitsRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppSettingsOrganizationRoute: typeof AuthenticatedAppSettingsOrganizationRoute
  AuthenticatedAppSettingsUsersRoute: typeof AuthenticatedAppSettingsUsersRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBookingsRoute: AuthenticatedAppBookingsRoute,
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppDealsRoute: AuthenticatedAppDealsRoute,
  AuthenticatedAppFollowUpsRoute: AuthenticatedAppFollowUpsRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRouteWithChildren,
  AuthenticatedAppOpportunitiesRoute: AuthenticatedAppOpportunitiesRoute,
  AuthenticatedAppPaymentsRoute: AuthenticatedAppPaymentsRoute,
  AuthenticatedAppPlotsRoute: AuthenticatedAppPlotsRoute,
  AuthenticatedAppProjectsRoute: AuthenticatedAppProjectsRoute,
  AuthenticatedAppQuotationsRoute: AuthenticatedAppQuotationsRoute,
  AuthenticatedAppReceiptsRoute: AuthenticatedAppReceiptsRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSiteVisitsRoute: AuthenticatedAppSiteVisitsRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppSettingsOrganizationRoute:
    AuthenticatedAppSettingsOrganizationRoute,
  AuthenticatedAppSettingsUsersRoute: AuthenticatedAppSettingsUsersRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
